window.SCRAPER_LINKS = {
  "The Odyssey": "https://t.me/KiksLabMovies",
  "Descendants: Wicked Wonderland": "https://t.me/KiksLabMovies",
  "Backrooms": "https://t.me/KiksLabMovies",
  "Obsession": "https://t.me/KiksLabMovies",
  "Me Before Me": "https://t.me/KiksLabMovies",
  "23 000 Lives": "https://t.me/KiksLabMovies",
  "Heartstopper Forever": "https://t.me/KiksLabMovies",
  "Moana": "https://t.me/KiksLabMovies",
  "Hope": "https://t.me/KiksLabMovies",
  "Spider-Man: Brand New Day": "https://t.me/KiksLabMovies",
  "Toy Story 5": "https://t.me/KiksLabMovies",
  "They Fight": "https://t.me/KiksLabMovies",
  "Desire": "https://t.me/KiksLabMovies",
  "Evil Dead Burn": "https://t.me/KiksLabMovies",
  "The Furious": "https://t.me/KiksLabMovies",
  "Normal": "https://t.me/KiksLabMovies",
  "Michael": "https://t.me/KiksLabMovies",
  "The Invite": "https://t.me/KiksLabMovies",
  "The Breadwinner": "https://t.me/KiksLabMovies",
  "The Drama": "https://t.me/KiksLabMovies",
  "Disclosure Day": "https://t.me/KiksLabMovies",
  "Scary Movie": "https://t.me/KiksLabMovies",
  "Passenger": "https://t.me/KiksLabMovies",
  "The Devil Wears Prada 2": "https://t.me/KiksLabMovies",
  "Project Hail Mary": "https://t.me/KiksLabMovies",
  "Your Heart Will Be Broken": "https://t.me/KiksLabMovies",
  "Mortal Kombat II": "https://t.me/KiksLabMovies",
  "Citizen Vigilante": "https://t.me/KiksLabMovies",
  "Avatar: Fire and Ash": "https://t.me/KiksLabMovies",
  "Deep Water": "https://t.me/KiksLabMovies",
  "The Get Out": "https://t.me/KiksLabMovies",
  "The Shawshank Redemption": "https://t.me/KiksLabMovies",
  "Avatar Aang: The Last Airbender": "https://t.me/KiksLabMovies",
  "Black Box": "https://t.me/KiksLabMovies",
  "Night of the Living Dead": "https://t.me/KiksLabMovies",
  "Kung Fu Soccer": "https://t.me/KiksLabMovies",
  "Peddi": "https://t.me/KiksLabMovies",
  "Summerween": "https://t.me/KiksLabMovies",
  "Little Brother": "https://t.me/KiksLabMovies",
  "Demon Slayer: Kimetsu no Yaiba Infinity Castle": "https://t.me/KiksLabMovies",
  "Spirited Away": "https://t.me/KiksLabMovies",
  "Detective Conan: Fallen Angel of the Highway": "https://t.me/KiksLabMovies",
  "Chainsaw Man - The Movie: Reze Arc": "https://t.me/KiksLabMovies",
  "Your Name.": "https://t.me/KiksLabMovies",
  "Solo Leveling -ReAwakening-": "https://t.me/KiksLabMovies",
  "Unanswered//butterfly": "https://t.me/KiksLabMovies",
  "JUJUTSU KAISEN: Execution": "https://t.me/KiksLabMovies",
  "Howl's Moving Castle": "https://t.me/KiksLabMovies",
  "Ten Count": "https://t.me/KiksLabMovies",
  "Milky☆Subway: The Galactic Limited Express - the Movie": "https://t.me/KiksLabMovies",
  "Princess Mononoke": "https://t.me/KiksLabMovies",
  "ONE PIECE HEROINES": "https://t.me/KiksLabMovies",
  "My Neighbor Totoro": "https://t.me/KiksLabMovies",
  "Perfect Blue": "https://t.me/KiksLabMovies",
  "Ghost in the Shell": "https://t.me/KiksLabMovies",
  "Neon Genesis Evangelion: The End of Evangelion": "https://t.me/KiksLabMovies",
  "A Silent Voice: The Movie": "https://t.me/KiksLabMovies",
  "Midori": "https://t.me/KiksLabMovies",
  "Akira": "https://t.me/KiksLabMovies",
  "The Avengers": "https://t.me/KiksLabMovies",
  "Avengers: Doomsday": "https://t.me/KiksLabMovies",
  "Avengers: Infinity War": "https://t.me/KiksLabMovies",
  "Avengers: Endgame": "https://t.me/KiksLabMovies",
  "Avengers: Age of Ultron": "https://t.me/KiksLabMovies",
  "Avengers: Secret Wars": "https://t.me/KiksLabMovies",
  "Crippled Avengers": "https://t.me/KiksLabMovies",
  "Avengers Grimm": "https://t.me/KiksLabMovies",
  "Alien Avengers": "https://t.me/KiksLabMovies",
  "Bikini Avengers": "https://t.me/KiksLabMovies",
  "Avengers Confidential: Black Widow & Punisher": "https://t.me/KiksLabMovies",
  "Masked Avengers": "https://t.me/KiksLabMovies",
  "Ultimate Avengers 2": "https://t.me/KiksLabMovies",
  "Ultimate Avengers: The Movie": "https://t.me/KiksLabMovies",
  "Shaolin Avengers": "https://t.me/KiksLabMovies",
  "LEGO Marvel Avengers: Mission Demolition": "https://t.me/KiksLabMovies",
  "The Three Avengers": "https://t.me/KiksLabMovies",
  "Next Avengers: Heroes of Tomorrow": "https://t.me/KiksLabMovies"
};
